# Generated by Django 4.2.7 on 2025-09-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_terms_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_categories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
