# Generated by Django 4.2.24 on 2025-09-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_users_is_acti_33e113_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_33e113_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_staf_b59a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_usernam_baeb4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_jo_c97edd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_created_dcdedc_idx',
        ),
    ]
