# Generated by Django 4.2.7 on 2025-09-02 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='payment ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='currency')),
                ('method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('digital_wallet', 'Digital Wallet'), ('cryptocurrency', 'Cryptocurrency')], max_length=20, verbose_name='method')),
                ('provider', models.CharField(choices=[('wompi', 'Wompi'), ('mercadopago', 'MercadoPago'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], max_length=20, verbose_name='provider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('provider_payment_id', models.CharField(blank=True, max_length=200, verbose_name='provider payment ID')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='provider transaction ID')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='provider response')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='card last four')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='card brand')),
                ('card_exp_month', models.CharField(blank=True, max_length=2, verbose_name='card exp month')),
                ('card_exp_year', models.CharField(blank=True, max_length=4, verbose_name='card exp year')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=100, unique=True, verbose_name='refund ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('reason', models.TextField(verbose_name='reason')),
                ('provider_refund_id', models.CharField(blank=True, max_length=200, verbose_name='provider refund ID')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='provider response')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('digital_wallet', 'Digital Wallet'), ('cryptocurrency', 'Cryptocurrency')], max_length=20, verbose_name='type')),
                ('provider', models.CharField(choices=[('wompi', 'Wompi'), ('mercadopago', 'MercadoPago'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], max_length=20, verbose_name='provider')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('card_last_four', models.CharField(max_length=4, verbose_name='card last four')),
                ('card_brand', models.CharField(max_length=20, verbose_name='card brand')),
                ('card_exp_month', models.CharField(max_length=2, verbose_name='card exp month')),
                ('card_exp_year', models.CharField(max_length=4, verbose_name='card exp year')),
                ('card_holder_name', models.CharField(max_length=150, verbose_name='card holder name')),
                ('provider_payment_method_id', models.CharField(max_length=200, verbose_name='provider payment method ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'provider'], name='payments_status_b774fe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
    ]
