# Generated by Django 4.2.24 on 2025-09-17 22:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_remove_order_orders_status_7dca14_idx_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total Transacciones')),
                ('successful_transactions', models.PositiveIntegerField(default=0, verbose_name='Transacciones Exitosas')),
                ('failed_transactions', models.PositiveIntegerField(default=0, verbose_name='Transacciones Fallidas')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Total')),
                ('by_provider', models.JSONField(blank=True, null=True, verbose_name='Por Proveedor')),
                ('by_status', models.JSONField(blank=True, null=True, verbose_name='Por Estado')),
                ('hourly_breakdown', models.JSONField(blank=True, null=True, verbose_name='Desglose por Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Métrica de Pago',
                'verbose_name_plural': 'Métricas de Pagos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactionLog',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, verbose_name='Trace ID')),
                ('event_type', models.CharField(choices=[('payment_initiated', 'Pago Iniciado'), ('payment_processing', 'Pago Procesando'), ('payment_success', 'Pago Exitoso'), ('payment_failed', 'Pago Fallido'), ('payment_cancelled', 'Pago Cancelado'), ('payment_refunded', 'Pago Reembolsado'), ('webhook_received', 'Webhook Recibido'), ('webhook_processed', 'Webhook Procesado'), ('retry_attempt', 'Intento de Reintento'), ('circuit_breaker_open', 'Circuit Breaker Abierto'), ('circuit_breaker_closed', 'Circuit Breaker Cerrado')], max_length=50, verbose_name='Tipo de Evento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('payment_id', models.CharField(db_index=True, max_length=100, verbose_name='Payment ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID')),
                ('provider', models.CharField(blank=True, max_length=20, null=True, verbose_name='Proveedor')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos')),
                ('environment', models.CharField(default='development', max_length=20, verbose_name='Ambiente')),
            ],
            options={
                'verbose_name': 'Log de Transacción',
                'verbose_name_plural': 'Logs de Transacciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reembolso', 'verbose_name_plural': 'Reembolsos'},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_status_b774fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_order_i_3d4604_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_01767a_idx',
            old_name='payments_user_id_1b771c_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_exp_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_exp_year',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_last_four',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='type',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='uuid',
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.CharField(default='COP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='refund',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadatos'),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='COP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Procesado en'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('wompi', 'Wompi'), ('mercadopago', 'MercadoPago'), ('stripe', 'Stripe')], max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Proveedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Respuesta del Proveedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Transacción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_exp_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes de Expiración'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_exp_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de Expiración'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Titular'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 Dígitos'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Por Defecto'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('wompi', 'Wompi'), ('mercadopago', 'MercadoPago'), ('stripe', 'Stripe')], max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider_payment_method_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Método en el Proveedor'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('card', 'Tarjeta de Crédito/Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('digital_wallet', 'Billetera Digital'), ('cash', 'Efectivo')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Procesado en'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Reembolso en el Proveedor'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='provider_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Respuesta del Proveedor'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Refund ID'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'provider_payment_method_id')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payments_pa_user_id_bd2d73_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['provider', 'is_active'], name='payments_pa_provide_56b8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['created_at'], name='payments_pa_created_5225c8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='payments_re_payment_4444a0_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user', 'status'], name='payments_re_user_id_47a120_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['created_at'], name='payments_re_created_d6a5d3_idx'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refund',
            table=None,
        ),
        migrations.AddIndex(
            model_name='paymenttransactionlog',
            index=models.Index(fields=['trace_id', 'timestamp'], name='payments_pa_trace_i_bc5bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransactionlog',
            index=models.Index(fields=['payment_id', 'timestamp'], name='payments_pa_payment_a30a26_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransactionlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='payments_pa_event_t_77fe86_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransactionlog',
            index=models.Index(fields=['provider', 'timestamp'], name='payments_pa_provide_bebfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransactionlog',
            index=models.Index(fields=['timestamp'], name='payments_pa_timesta_1fdf26_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmetrics',
            index=models.Index(fields=['date'], name='payments_pa_date_105ef1_idx'),
        ),
    ]
