# Generated by Django 4.2.24 on 2025-09-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'sort_order'], name='brands_is_acti_a0aad7_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name', 'is_active'], name='brands_name_6c8691_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='brands_slug_6a4b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active', 'sort_order'], name='categories_parent__4b25a2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='categories_is_acti_3acc57_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'is_active'], name='categories_name_7b882a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['is_active', 'sort_order'], name='colors_is_acti_36dff3_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['name', 'is_active'], name='colors_name_bfe427_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['type', 'is_active', 'sort_order'], name='sizes_type_a1d8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['is_active', 'type'], name='sizes_is_acti_97f1c4_idx'),
        ),
    ]
