# Generated by Django 4.2.24 on 2025-09-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_brand_brands_is_acti_a0aad7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brands_is_acti_a0aad7_idx',
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='brands_name_6c8691_idx',
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='brands_slug_6a4b1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_parent__4b25a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_is_acti_3acc57_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_name_7b882a_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_slug_b4303a_idx',
        ),
        migrations.RemoveIndex(
            model_name='color',
            name='colors_is_acti_36dff3_idx',
        ),
        migrations.RemoveIndex(
            model_name='color',
            name='colors_name_bfe427_idx',
        ),
        migrations.RemoveIndex(
            model_name='size',
            name='sizes_type_a1d8f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='size',
            name='sizes_is_acti_97f1c4_idx',
        ),
    ]
