# Generated by Django 4.2.7 on 2025-09-02 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('products', 'Products Report'), ('users', 'Users Report'), ('inventory', 'Inventory Report'), ('custom', 'Custom Report')], max_length=20, verbose_name='report type')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='is scheduled')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='schedule frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
