# Generated by Django 4.2.7 on 2025-09-03 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user_message', 'User Message'), ('admin_response', 'Admin Response'), ('system_notification', 'System Notification')], default='user_message', max_length=20, verbose_name='message type')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_messages', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.claim', verbose_name='claim')),
            ],
            options={
                'verbose_name': 'Claim Message',
                'verbose_name_plural': 'Claim Messages',
                'db_table': 'claim_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
