# Generated by Django 4.2.7 on 2025-09-08 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_document_id_order_first_name_order_last_name'),
        ('products', '0006_remove_product_products_price_fe467e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Incremento'), ('decrease', 'Decremento'), ('set', 'Establecer')], max_length=20, verbose_name='adjustment type')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='products.product', verbose_name='product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'db_table': 'inventory_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('consumed', 'Consumida'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'db_table': 'stock_reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='stock_reser_user_id_faf9ed_idx'), models.Index(fields=['expires_at', 'status'], name='stock_reser_expires_789668_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock Bajo'), ('out_of_stock', 'Sin Stock'), ('overstock', 'Sobrestock')], max_length=20, verbose_name='alert type')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta')], default='active', max_length=20, verbose_name='status')),
                ('current_quantity', models.PositiveIntegerField(verbose_name='current quantity')),
                ('threshold_quantity', models.PositiveIntegerField(verbose_name='threshold quantity')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product', verbose_name='product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'db_table': 'stock_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='stock_alert_status_1b65ce_idx'), models.Index(fields=['alert_type', 'status'], name='stock_alert_alert_t_f0dd02_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjustment', 'Ajuste'), ('transfer', 'Transferencia'), ('return', 'Devolución')], max_length=20, verbose_name='movement type')),
                ('reason', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('return', 'Devolución'), ('adjustment', 'Ajuste manual'), ('transfer', 'Transferencia'), ('damage', 'Daño'), ('expired', 'Vencido'), ('theft', 'Robo'), ('other', 'Otro')], max_length=20, verbose_name='reason')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost per unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order', verbose_name='order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.orderitem', verbose_name='order item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_m_product_cf6250_idx'), models.Index(fields=['variant', 'created_at'], name='inventory_m_variant_23b28d_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_m_movemen_fbb0aa_idx')],
            },
        ),
    ]
