from django.db import models
from django.utils.translation import gettext_lazy as _
from ecommerce.apps.users.models import User


class Report(models.Model):
    """
    Modelo para reportes del sistema.
    """
    REPORT_TYPES = [
        ('sales', _('Sales Report')),
        ('products', _('Products Report')),
        ('users', _('Users Report')),
        ('inventory', _('Inventory Report')),
        ('custom', _('Custom Report')),
    ]
    
    name = models.CharField(_('name'), max_length=200)
    report_type = models.CharField(_('report type'), max_length=20, choices=REPORT_TYPES)
    generated_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='generated_reports',
        verbose_name=_('generated by')
    )
    data = models.JSONField(_('data'), default=dict)
    filters = models.JSONField(_('filters'), default=dict, blank=True)
    is_scheduled = models.BooleanField(_('is scheduled'), default=False)
    schedule_frequency = models.CharField(
        _('schedule frequency'),
        max_length=20,
        choices=[
            ('daily', _('Daily')),
            ('weekly', _('Weekly')),
            ('monthly', _('Monthly')),
        ],
        blank=True
    )
    
    # Timestamps
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)
    
    class Meta:
        verbose_name = _('Report')
        verbose_name_plural = _('Reports')
        db_table = 'reports'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name