# Generated by Django 4.2.7 on 2025-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_id',
            field=models.CharField(default='', max_length=20, verbose_name='document ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='last name'),
        ),
    ]
