# Generated by Django 4.2.24 on 2025-09-17 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_document_id_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_status_7dca14_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_user_id_17dbdf_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación lógica', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el objeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el objeto ha sido eliminado lógicamente', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='updated at'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'created_at'], name='orders_user_id_288b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'payment_status', 'created_at'], name='orders_user_id_8b3461_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status', 'created_at'], name='orders_status_1b8442_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='orders_created_bb75aa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email', 'status'], name='orders_email_cae8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'status'], name='orders_is_dele_86b04a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status', 'payment_status'], name='orders_created_fb9964_idx'),
        ),
    ]
