# Generated by Django 4.2.7 on 2025-09-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='eCommerce Admin', max_length=200, verbose_name='site name')),
                ('site_description', models.TextField(blank=True, verbose_name='site description')),
                ('site_url', models.URLField(default='http://localhost:3000', verbose_name='site URL')),
                ('admin_email', models.EmailField(default='admin@admin.com', max_length=254, verbose_name='admin email')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='email host')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='email port')),
                ('email_username', models.CharField(blank=True, max_length=200, verbose_name='email username')),
                ('email_password', models.CharField(blank=True, max_length=200, verbose_name='email password')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='email use TLS')),
                ('session_timeout', models.PositiveIntegerField(default=30, verbose_name='session timeout')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, verbose_name='max login attempts')),
                ('password_min_length', models.PositiveIntegerField(default=8, verbose_name='password min length')),
                ('require_2fa', models.BooleanField(default=False, verbose_name='require 2FA')),
                ('max_products_per_page', models.PositiveIntegerField(default=20, verbose_name='max products per page')),
                ('enable_reviews', models.BooleanField(default=True, verbose_name='enable reviews')),
                ('enable_wishlist', models.BooleanField(default=True, verbose_name='enable wishlist')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='enable notifications')),
                ('order_auto_confirm', models.BooleanField(default=False, verbose_name='order auto confirm')),
                ('order_auto_cancel_hours', models.PositiveIntegerField(default=24, verbose_name='order auto cancel hours')),
                ('enable_tracking', models.BooleanField(default=True, verbose_name='enable tracking')),
                ('payment_gateway', models.CharField(default='wompi', max_length=50, verbose_name='payment gateway')),
                ('payment_test_mode', models.BooleanField(default=True, verbose_name='payment test mode')),
                ('currency', models.CharField(default='COP', max_length=10, verbose_name='currency')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='push notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
                'db_table': 'admin_settings',
            },
        ),
    ]
