# Generated by Django 4.2.24 on 2025-09-17 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTPDevice',
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
        migrations.RemoveField(
            model_name='usersecurityprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='usersecurityprofile',
            name='backup_codes',
        ),
    ]
