# Generated by Django 4.2.24 on 2025-09-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_2fa_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Exitoso'), ('login_failed', 'Login Fallido'), ('password_changed', 'Contraseña Cambiada'), ('account_locked', 'Cuenta Bloqueada'), ('account_unlocked', 'Cuenta Desbloqueada'), ('suspicious_activity', 'Actividad Sospechosa'), ('admin_access', 'Acceso de Administrador'), ('data_export', 'Exportación de Datos'), ('api_access', 'Acceso a API')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserSecurityProfile',
        ),
    ]
