# Generated by Django 4.2.7 on 2025-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('unisex', 'Unisex')], help_text='Género del producto', max_length=20, verbose_name='gender'),
        ),
    ]
