# Generated by Django 4.2.7 on 2025-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen específica para esta variante', null=True, upload_to='products/variants/', verbose_name='variant image'),
        ),
    ]
