# Generated by Django 4.2.7 on 2025-09-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttagrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producttagrelation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttagrelation',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.DeleteModel(
            name='ProductTagRelation',
        ),
    ]
