# Generated by Django 4.2.7 on 2025-09-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_is_featured_alter_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_price_fe467e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_e1ba5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_name_6f9890_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='product_ima_product_c8c86a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='product_ima_product_66d32e_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='product_rev_product_eb9ba2_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='product_rev_user_id_c450e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='product_rev_rating_fb8943_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_product_b96575_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_size_id_af0de5_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_sku_3a95f0_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='is approved'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
